// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi2_GhciJhY3gTpwzykk_iTG287h7UEBI',
    appId: '1:142814119034:web:c5e40747c35660434ae7c3',
    messagingSenderId: '142814119034',
    projectId: 'peaceful-pulse-35af5',
    authDomain: 'peaceful-pulse-35af5.firebaseapp.com',
    storageBucket: 'peaceful-pulse-35af5.appspot.com',
    measurementId: 'G-R0JYZN7QPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVt8Zn1XIMA8pTtBl9v6TyewWq5kqdUqM',
    appId: '1:142814119034:android:7ddcc8151cdab0c34ae7c3',
    messagingSenderId: '142814119034',
    projectId: 'peaceful-pulse-35af5',
    storageBucket: 'peaceful-pulse-35af5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUTgMBYeXOnxc4vtT2m1pzD38MhXqXGTk',
    appId: '1:142814119034:ios:04d31c43f0ccf80d4ae7c3',
    messagingSenderId: '142814119034',
    projectId: 'peaceful-pulse-35af5',
    storageBucket: 'peaceful-pulse-35af5.appspot.com',
    iosBundleId: 'com.example.peacefulPulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUTgMBYeXOnxc4vtT2m1pzD38MhXqXGTk',
    appId: '1:142814119034:ios:04d31c43f0ccf80d4ae7c3',
    messagingSenderId: '142814119034',
    projectId: 'peaceful-pulse-35af5',
    storageBucket: 'peaceful-pulse-35af5.appspot.com',
    iosBundleId: 'com.example.peacefulPulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi2_GhciJhY3gTpwzykk_iTG287h7UEBI',
    appId: '1:142814119034:web:310e39e0eba509d84ae7c3',
    messagingSenderId: '142814119034',
    projectId: 'peaceful-pulse-35af5',
    authDomain: 'peaceful-pulse-35af5.firebaseapp.com',
    storageBucket: 'peaceful-pulse-35af5.appspot.com',
    measurementId: 'G-E0BZ3EKQBM',
  );
}
